### ISSUE TITLE
Error after running make command

### ISSUE THREAD

**Issue by babyfaceEasy** [Ch3ck/github-bot#3]
Whenever i run the command 'make', i get these 2 errors;
./main.go:85:9 usr decleared and not used
Makefile:13: recipe for target 'build' failed

**Comment by Ch3ck** [comment]
Let me work on this now @babyfaceEasy

**Comment by Ch3ck** [comment]
Issue Fixed here: https://github.com/Ch3ck/github-bot/commit/541ff066d1ff315cf9cff09e2df241604e57dbc4
